### ISSUE TITLE
How to use `cmd` with `jpm build`?

### ISSUE THREAD

**Issue by CFiggers** [ianthehenry/cmd#1]
It seems like the focus of `cmd` at present is on shebang-style Janet scripts. But I'm trying to build native executables with `jpm`. I haven't been able to get even a "Hello, World" working based on the instructions in the README. Could you please point me in the right direction?

**Comment by ianthehenry** [comment]
Oh hi! It looks like there's a problem with how `cmd` normalizes arguments when used in compiled mode that I just fixed in a601d277ffd6e9608fc22ab48dc90cf13750f483. I also added an example of `cmd/main` to the readme, which you need to use to make a compiled executable, and this fact was completely hidden.

Not sure which of those (or both!) was giving you trouble, but could you try `v1.0.3` and see if it works for you?

**Comment by ianthehenry** [comment]
Actually, belay that order. Looks like I still have an issue...

**Comment by CFiggers** [comment]
Belaying, sir 🫡

**Comment by ianthehenry** [comment]
Okay! It worked but `--help` didn't. Both should work in `v1.0.4` now. (Sorry for the delay; I had to eat dinner.)

**Comment by CFiggers** [comment]
No need to apologize, man—dinner is important!

Is this the behavior I should be expecting?

![image](https://user-images.githubusercontent.com/55862180/231635369-2f38b43b-e69e-4a64-a11b-5dbc91ad72e2.png)

**Comment by ianthehenry** [comment]
:( no

I mean, yes, that is how it works, but no, you should not expect it to work like that because it's dumb that it does that.

The subcommand parser doesn't handle any flags correctly; it just looks for a literal matching string. It should definitely handle `--help` and `-h` like regular commands do. I created a separate issue to track this: #2

**Comment by ianthehenry** [comment]
(to be clear the issue was with `--help` for non-`cmd/group` commands -- `--help` for groups has never worked correctly in any mode)

**Comment by CFiggers** [comment]
Makes sense to me!

Since the focus of this issue is the problem with compiled executables, and since that problem seems to be fixed now, I'll go ahead and close this issue. Thanks for your help!
